### ISSUE TITLE
respond!

### ISSUE THREAD

**Issue by OwnerSCIFahrul** [Mahmoud-Italy/real-time-Private-Chat-using-Socket.io-Nodejs-mySql#1]
how mysql.sql? code query create table?

**Comment by Mahmoud-Italy** [comment]
var mysql = require('mysql');

var db = mysql.createConnection({
  host: "localhost",
  user: "yourusername",
  password: "yourpassword",
  database: "mydb"
});

db.connect(function(err) {
  if (err) throw err;
  console.log("Connected!");
  var sql = "CREATE TABLE tableName (name VARCHAR(255), address VARCHAR(255))";
  db.query(sql, function (err, result) {
    if (err) throw err;
    console.log("Table created");
  });
});
